# Angular App configuration for production
FROM node:24 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:prod

# Serve app with nginx
FROM nginx:alpine

COPY --from=build /app/dist/task-admin-frontend/browser /usr/share/nginx/html

# For mapping routes that depends on params
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
